# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/init.ipynb (unless otherwise specified).

__all__ = ['start_log', 'NEO4J_VERSION']

# Cell

#NEO4J_VERSION = '3.5.3'
NEO4J_VERSION = '4.3.2'

import logging

def start_log(logger_name=None):
    '''
    Start a log that prints to stdout
    '''
    logger = logging.getLogger(logger_name)
    screen_handler = logging.StreamHandler()
    formatter = logging.Formatter(
            fmt='[%(levelname)s] %(module)s(%(funcName)s)%(asctime)s--> %(lineno)s.\t %(message)s')
    screen_handler.setFormatter(formatter)
    if not logger.handlers:
        logger.addHandler(screen_handler)
    logger.setLevel(logging.DEBUG)
    return logger

# Cell
from .db import Query