# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"uniqueness": "constraints.ipynb",
         "logger": "db.ipynb",
         "DEFAULT_AUTH": "db.ipynb",
         "neo_uri": "db.ipynb",
         "neo_auth": "db.ipynb",
         "uri": "db.ipynb",
         "BoltConnectionUnsuccessful": "db.ipynb",
         "MultipleSearchResults": "db.ipynb",
         "NoSearchResults": "db.ipynb",
         "make_driver": "db.ipynb",
         "set_default_driver": "db.ipynb",
         "default_driver": "db.ipynb",
         "tearDown": "db.ipynb",
         "DEFAULT_DRIVER": "db.ipynb",
         "Query": "db.ipynb",
         "node": "db.ipynb",
         "relationship": "db.ipynb",
         "MATCH": "db.ipynb",
         "RETURN": "db.ipynb",
         "WITH": "db.ipynb",
         "node_to_dict": "db.ipynb",
         "fetch": "db.ipynb",
         "link": "db.ipynb",
         "unlink": "db.ipynb",
         "NEO4J_VERSION": "init.ipynb",
         "create": "node.ipynb",
         "exists": "node.ipynb",
         "set_properties": "node.ipynb",
         "ensure": "node.ipynb",
         "txt": "node.ipynb",
         "get_properties": "node.ipynb",
         "is_test_data": "sandbox.ipynb",
         "is_empty": "sandbox.ipynb",
         "create_totem": "sandbox.ipynb",
         "NotTestDataset": "sandbox.ipynb",
         "start_fresh": "sandbox.ipynb",
         "run_neo4j": "sandbox.ipynb",
         "start_neo4j": "sandbox.ipynb"}

modules = ["constraints.py",
           "db.py",
           "__init__.py",
           "node.py",
           "sandbox.py"]

doc_url = "https://talosiot-will.github.io/mranderson/"

git_url = "https://github.com/talosiot-will/mranderson/tree/master/"

def custom_doc_links(name): return None
